### ISSUE TITLE
quadratic eq endpoint sync

### ISSUE THREAD

**Issue by ZsoltToth** [ZsoltToth/eku-intelligent-services#1]
As a user, I want to solve Quadratic Equations by calling an end point with query params (a,b,c).

AC:
 - Application listen of fix port
 - GET /qe/solve expects 3 query parameters (a,b,c)
 - 200 OK => JSON { solution: [x1, x2] , discriminant: double} 
 - 406 Not Acceptable => query params missing or a == 0.0

**Comment by judit0310** [comment]
Should I check, if the parameter is a number?

**Comment by ZsoltToth** [comment]
Yes, 406 should be OK I think.

**Comment by judit0310** [comment]
Thanks
