### ISSUE TITLE
Swagger for AI Service

### ISSUE THREAD

**Issue by ZsoltToth** [ZsoltToth/eku-intelligent-services#23]
As a developer, I would like to use Swagger on AI Server too.

See:
https://pypi.org/project/flask-swagger/#:~:text=Flask%2Dswagger%20provides%20a%20method,with%20Swagger%202.0%20Operation%20objects.&text=Flask%2Dswagger%20supports%20docstrings%20in,and%20regular%20Flask%20view%20functions.

AC:
 - Swagger docs loads on /api-host path

**Comment by judit0310** [comment]
The given code did not work on my computer. Talk about it tomorrow
